version: '3'

services:
  rabbitmq1:
    image: rabbitmq:3.13-management
    hostname: rabbitmq1 
    ports:
      - "5672:5672"  # Expose AMQP port
      - "15672:15672" # Expose management UI port
      - "5552:5552"
    environment:
      - RABBITMQ_ERLANG_COOKIE='your_secure_cookie' # Important for clustering
    networks:
      - rabbitmq-net

  # rabbitmq2:
  #   image: rabbitmq:3.13-management
  #   hostname: rabbitmq2 
  #   environment:
  #     - RABBITMQ_ERLANG_COOKIE='your_secure_cookie' # Same cookie as other nodes
  #   networks:
  #     - rabbitmq-net

  # rabbitmq3:
  #   image: rabbitmq:3.13-management
  #   hostname: rabbitmq3 
  #   environment:
  #     - RABBITMQ_ERLANG_COOKIE='your_secure_cookie'
  #   networks:
  #     - rabbitmq-net

networks:
  rabbitmq-net:
    driver: bridge 
